from unionfind.UnionFind import UnionFind

v = UnionFind(10)
# print(v.parents,v.all_group_members().values())
v.union(1,3)
# print(v.parents,v.all_group_members().values())
v.union(4,5)
# print(v.parents,v.all_group_members().values())
v.union(1,5)
v.union(1,1)
# print(v.parents,v.all_group_members().values())
v.union(6,7)
print(v.find(1))
print(v.find(3))
print(v.find(5))
print(v.find(6))
print("v.size(6) ",v.size(6))
# v.union(1,2)
# v.union(2,3)
print(v.all_group_members().values())
# v.union(1,3)
# v.union(1,1)
print(v.all_group_members().values())
print(v.group_count())
print(v.roots())
print(v.members(0))
print(v.members(1))
v.union(1,3)
# v2 = UnionFind([1,2,3,5,6])
# v2.union(1,2)
# print(v2.all_group_members().values())