from unionfind.UnionFind import UnionFind

v = UnionFind(10)
# print(v.parents,v.all_group_members().values())
v.union(1,3)
# print(v.parents,v.all_group_members().values())
v.union(4,5)
# print(v.parents,v.all_group_members().values())
v.union(1,5)
# print(v.parents,v.all_group_members().values())
v.union(6,7)
print(v.find(1))
print(v.find(3))
print(v.find(5))
print(v.find(6))
# v.union(1,2)
# v.union(2,3)
print(v.all_group_members().values())
# v.union(1,3)
# v.union(1,1)
print(v.all_group_members().values())
print(v.group_count())